# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gini_split_numeric <- function(x, order, y, nlevels) {
    .Call(`_woods_gini_split_numeric`, x, order, y, nlevels)
}

.igr_by_indices <- function(x, indices) {
    .Call(`_woods_igr_by_indices`, x, indices)
}

